name: Build and run tests

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

concurrency:
  group: golang-build-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21.1
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.1
        go-version-file: "go.mod"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: LOG_LEVEL="error" go test -p 1 -v -race -failfast -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Build
      run: go build -v .

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        token: ${{ secrets.CODECOV_TOKEN }}